# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mediawiki-Spider
version:      0.31
version_from: lib/Mediawiki/Spider.pm
installdirs:  site
requires:
    Data::Dumper:                  1
    HTML::Extract:                 0.1
    LWP::UserAgent:                2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
